version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      discovery.type: single-node
    ports:
      - "9201:9200"
      - "9301:9300"